### PR TITLE
Update dependencies, extract separator

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by pgilad** [comment]
Hey @HenrikJoreteg - can you review this?

**Comment by HenrikJoreteg** [comment]
published as `v1.2.1`

**Comment by HenrikJoreteg** [comment]
Thanks @pgilad I also added you as a collaborator and owner on npm. Feel free to do stuff :)

**Comment by pgilad** [comment]
Great, thanks for the trust on this one ;-)

**Pull request merged**
